gatling {
    environments {
        local {
            duration = 5
            totalTps = 1

            kafka {
                properties {
                    bootstrap.servers = ["localhost:9092"]
                    schema.registry.url = "http://localhost:8081"
                    security.protocol = "PLAINTEXT"

                    consumers {
                        default {
                            group.id = "test"
                            key.deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
                            value.deserializer = "io.confluent.kafka.serializers.KafkaAvroDeserializer"
                            isolationLevel = "read_committed"
                            poll.interval.ms = 100
                            session.timeout.ms = 10000
                        }
                    }

                    producers {
                        default {
                            key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
                            value.serializer = "io.confluent.kafka.serializers.KafkaAvroSerializer"
                        }
                    }
                }
                topics {
                    myTaskTopic = "test.v1"
                    outputTopic = "output.v1"
                }
            }
        }
    }
}